name: Deploy Clean Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clean-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean and build site
        run: python site-utils.py -o docs clean build

      - name: Set timestamp variable
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Checkout deploy branch
        run: |
          git fetch origin deploy
          git checkout deploy

      - name: Copy build artifacts into deploy branch
        run: |
          cp -r docs/* .

      - name: Commit and push to deploy
        run: |
          git add -A
          git commit -m "Deploy build: ${{ env.timestamp }}" || echo "No changes to commit"
          git push origin deploy
