name: Deploy Clean Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  clean-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean and build site
        run: python site-utils.py -o docs clean build

      - name: Set timestamp variable
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create timestamp branch and merge to deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "build-${{ env.timestamp }}"
          git add docs/*.html
          git commit -m "deployed build:${{ env.timestamp }}" || echo "No changes to commit"
          git push origin "build-${{ env.timestamp }}"
          git fetch origin deploy
          git checkout deploy
          git merge --allow-unrelated-histories -s ours "build-${{ env.timestamp }}" -m "Merge build branch into deploy (ignore build changes)"
          git push origin deploy

      - name: Remove timestamp build branch
        run: |
          git branch -D "build-${{ env.timestamp }}" || true
          git push origin --delete "build-${{ env.timestamp }}" || true
